### ISSUE TITLE
Issues with fetch Futures 

### ISSUE THREAD

**Issue by dsigler1234** [jump-dev/Xpress.jl#121]
Hi,
 I am working on a parallel implementation of ADMM where I solve JuMP models using Xpress on worker processes via Julia's Distributed library. I have noticed that when I used Xpress as the solver on worker process I cannot use basic JuMP functions on a model after it has been solved and fetched from the worker nodes. However such functionality does work with Ipopt so I think this might be an Xpress.jl issue. Here is a simple example:
```Julia
@everywhere using Pkg
for w in workers()
    @spawnat(w, Pkg.activate("/Users/dsigler/WaterModels.jl"))
end

@everywhere using JuMP
@everywhere using Ipopt
@everywhere using Xpress

@everywhere function test_function!(solver)
    
    if solver == "ipopt"
        model = Model(with_optimizer(Ipopt.Optimizer, print_level=0))
    elseif solver == "Xpress"
        model = Model(Xpress.Optimizer)
        JuMP.set_optimizer_attributes(model, "logfile" => "output.log")
    end
    
    @variable(model, x >= 0)
    @objective(model, Min, 2x)
    optimize!(model)

    return model
end

println(" ")
println("Ipopt Test")
test_dict = Dict();
solver = "ipopt";
println("using Ipopt on main worker")
test_dict["model"] = test_function!(solver);



println("here is the model")
println(test_dict["model"])
println(" ")

println("here is the objective value")
println(JuMP.objective_value(test_dict["model"]))
println(" ")

println("using Ipopt on worker 2")
test_dict["model"] = remotecall(test_function!,2,solver);
print(test_dict["model"])
println(" ")

println("here is the objective value")
println(JuMP.objective_value((fetch(test_dict["model"]))))
println(" ")

println("Xpress Test")
test_dict = Dict();
solver = "Xpress";
println(" now using Xpress on main worker")
test_dict["model"] = test_function!(solver);
println(" ")



println("here is the model")
println(test_dict["model"])
println(" ")

println("here is the objective value")
println(JuMP.objective_value(test_dict["model"]))
println(" ")

println("using xpress on worker 2")
test_dict["model"] = remotecall(test_function!,2,solver);
println(test_dict["model"])
println(" ")

println("here is the objective value")
println(JuMP.objective_value((fetch(test_dict["model"]))))
println(" ")
```

# Here is the output from the REPL

```Julia
julia> include("./xpress_error.jl")
      From worker 2:	  Activating environment at `~/WaterModels.jl/Project.toml`
      From worker 3:	  Activating environment at `~/WaterModels.jl/Project.toml`
 
Ipopt Test
using Ipopt on main worker
here is the model
Min 2 x
Subject to
 x ≥ 0.0

 
here is the objective value
-1.7494096423347506e-8
 
using Ipopt on worker 2
Future(2, 1, 268, nothing) 
here is the objective value
-1.7494096423347506e-8
 
Xpress Test
 now using Xpress on main worker
 
here is the model
Min 2 x
Subject to
 x ≥ 0.0

 
here is the objective value
0.0
 
using xpress on worker 2
Future(2, 1, 270, nothing)
 
here is the objective value
ERROR: LoadError: XpressError(255): Unrecoverable error. Received null pointer in CWrapper. Something must be wrong.
Stacktrace:
  [1] unsafe_convert
    @ ~/.julia/packages/Xpress/ab5Cg/src/helper.jl:51 [inlined]
  [2] XPRSgetintattrib(prob::Xpress.XpressProblem, _index::Int64, _ivalue::Base.RefValue{Int32})
    @ Xpress.Lib ~/.julia/packages/Xpress/ab5Cg/src/lib.jl:130
  [3] invoke(::Function, ::Int64, ::Type{Int64}, ::Xpress.XpressProblem, ::Vararg{Any, N} where N)
    @ Xpress ~/.julia/packages/Xpress/ab5Cg/src/utils.jl:17
  [4] getintattrib
    @ ~/.julia/packages/Xpress/ab5Cg/src/api.jl:373 [inlined]
  [5] get(model::Xpress.Optimizer, attr::MathOptInterface.TerminationStatus)
    @ Xpress ~/.julia/packages/Xpress/ab5Cg/src/MOI/MOI_wrapper.jl:2348
  [6] get(b::MathOptInterface.Bridges.LazyBridgeOptimizer{Xpress.Optimizer}, attr::MathOptInterface.TerminationStatus)
    @ MathOptInterface.Bridges ~/.julia/packages/MathOptInterface/5WwpK/src/Bridges/bridge_optimizer.jl:719
  [7] get(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, attr::MathOptInterface.TerminationStatus)
    @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/5WwpK/src/Utilities/cachingoptimizer.jl:706
  [8] _moi_get_result(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, args::MathOptInterface.ObjectiveValue)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/JuMP.jl:1084
  [9] get(model::Model, attr::MathOptInterface.ObjectiveValue)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/JuMP.jl:1100
 [10] objective_value(model::Model; result::Int64)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/objective.jl:42
 [11] objective_value(model::Model)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/objective.jl:42
 [12] top-level scope
    @ ~/ADMM.jl/experimental/ParConsensusADMM/examples/xpress_error.jl:77
 [13] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [14] top-level scope
    @ REPL[1]:1
in expression starting at /Users/dsigler/ADMM.jl/experimental/ParConsensusADMM/examples/xpress_error.jl:77
```

**Comment by odow** [comment]
Xpress.jl does some things with the license initialization, so I wouldn't be surprised if it isn't thread-safe. 

Or it might be this:
https://github.com/jump-dev/Xpress.jl/blob/6f95f15d1c87eed35419c0e6e09098efa78691c9/src/helper.jl#L49-L53

I just merged documentation on how to wrap a C optimizer
https://jump.dev/MathOptInterface.jl/dev/manual/implementing/#Optimizer-objects-for-C-solvers

What happens if you change
```Julia
@everywhere using Xpress
```
to 
```Julia
@everywhere begin
    using Xpress
    Base.cconvert(::Type{Ptr{Cvoid}}, x::Xpress.CWrapper) = x
end
```

**Comment by dsigler1234** [comment]
Still throws this error:

here is the objective value
ERROR: LoadError: XpressError(255): Unrecoverable error. Received null pointer in CWrapper. Something must be wrong.
Stacktrace:
  [1] unsafe_convert
    @ ~/.julia/packages/Xpress/ab5Cg/src/helper.jl:51 [inlined]
  [2] XPRSgetintattrib(prob::Xpress.XpressProblem, _index::Int64, _ivalue::Base.RefValue{Int32})
    @ Xpress.Lib ~/.julia/packages/Xpress/ab5Cg/src/lib.jl:130
  [3] invoke(::Function, ::Int64, ::Type{Int64}, ::Xpress.XpressProblem, ::Vararg{Any, N} where N)
    @ Xpress ~/.julia/packages/Xpress/ab5Cg/src/utils.jl:17
  [4] getintattrib
    @ ~/.julia/packages/Xpress/ab5Cg/src/api.jl:373 [inlined]
  [5] get(model::Xpress.Optimizer, attr::MathOptInterface.TerminationStatus)
    @ Xpress ~/.julia/packages/Xpress/ab5Cg/src/MOI/MOI_wrapper.jl:2348
  [6] get(b::MathOptInterface.Bridges.LazyBridgeOptimizer{Xpress.Optimizer}, attr::MathOptInterface.TerminationStatus)
    @ MathOptInterface.Bridges ~/.julia/packages/MathOptInterface/5WwpK/src/Bridges/bridge_optimizer.jl:719
  [7] get(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, attr::MathOptInterface.TerminationStatus)
    @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/5WwpK/src/Utilities/cachingoptimizer.jl:706
  [8] _moi_get_result(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, args::MathOptInterface.ObjectiveValue)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/JuMP.jl:1084
  [9] get(model::Model, attr::MathOptInterface.ObjectiveValue)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/JuMP.jl:1100
 [10] objective_value(model::Model; result::Int64)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/objective.jl:42
 [11] objective_value(model::Model)
    @ JuMP ~/.julia/packages/JuMP/MIPb6/src/objective.jl:42
 [12] top-level scope
    @ ~/ADMM.jl/experimental/ParConsensusADMM/examples/xpress_error.jl:81
 [13] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [14] top-level scope
    @ REPL[1]:1
in expression starting at /Users/dsigler/ADMM.jl/experimental/ParConsensusADMM/examples/xpress_error.jl:81

**Comment by odow** [comment]
Ah. I took another look at your code. Your issue is likely that the remote worker GCs the model, so when `fetch` gets called the inner model doesn't exist. I don't know why this happens, or if it's expected behavior.

Either turn of the GC `GC.enable(false)`, or restructure your code to avoid futures. Just use `remotecall_fetch` to return the objective value from the worker instead of the full model.

**Comment by dsigler1234** [comment]
Hummm ok. So I tried replacing the end of my code example with
GC.enable(false)
println("using xpress on worker 2")
test_dict["model"] = remotecall(test_function!,2,solver);
println(test_dict["model"])
println(" ")


println("here is the objective value")
println(JuMP.objective_value((fetch(test_dict["model"]))))
println(" ")
GC.enable(true)

and got the same error. Also if GC was really the problem wouldn't the Ipopt case also fail or am I missing something?

**Comment by odow** [comment]
> Also if GC was really the problem wouldn't the Ipopt case also fail or am I missing something?

No. Ipopt caches the solution after a solve so it doesn't matter if the pointer gets freed.

Restructure your code so you aren't calling moving `model` between processes.

**Comment by dsigler1234** [comment]
Ok sounds good. Thanks for your help!

**Comment by joaquimg** [comment]
Not moving `model` between processes is the solution to all problems here?
( not moving is JuMP recommendation, right? )
